[package]
name = "rpi-eeprom"
version.workspace = true
edition = "2021"
authors = ["MDMA Development Team"]
repository = "https://github.com/johlrogge/modular-digital-music-array"
license = "MIT"

[package.metadata.polylith]
interface = "rpi-eeprom"

[dependencies]
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
