[package]
name = "media-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata]

[package.metadata.polylith]
interface = "media-client"

[dependencies]
media-protocol = { path = "../media_protocol" }
playback-primitives = { path = "../playback_primitives" }
nng-transport = { path = "../nng_transport" }
nng = { workspace = true }
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
