[package]
name = "mdma-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "mdma"
path = "src/main.rs"

[dependencies]
client = { path = "../../bases/client" }
clap = { workspace = true }
clap_complete = { workspace = true }
color-eyre = { workspace = true }
event-protocol = { path = "../../components/event_protocol" }
inbox-utils = { path = "../../components/inbox_utils" }
mdma-client = { path = "../../components/mdma_client" }
tempfile = { workspace = true }
nng = { workspace = true }
nng-transport = { path = "../../components/nng_transport" }
serde_json = { workspace = true }
audio-transcoder = { path = "../../components/audio_transcoder" }
library-ipc-client = { path = "../../components/library_ipc_client" }
library-search = { path = "../../components/library_search" }
source-protocol = { path = "../../components/source_protocol" }
reqwest = { version = "0.12", default-features = false, features = ["blocking", "rustls-tls"] }
colored = "2.0"
corsett = { workspace = true }
terminal_size = "0.4"

[dev-dependencies]
pretty_assertions = { workspace = true }
