[package]
name = "mdma-bdd"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "mdma_bdd"
path = "src/lib.rs"

[[test]]
name = "cucumber"
harness = false

[dependencies]
cucumber = "0.21"
tokio = { version = "1.36", features = ["full"] }
tempfile = "3"
mdma-client = { path = "../../components/mdma_client" }
date-expression = { path = "../../components/date_expression" }
media-protocol = { path = "../../components/media_protocol" }
playback-primitives = { path = "../../components/playback_primitives" }
library-ipc-protocol = { path = "../../components/library_ipc_protocol" }
stainless-facts = { git = "https://github.com/johlrogge/stainless_facts", rev = "2aa820a808fd5345a1bd59c11d90969bfa84b285" }
music-facts = { path = "../../components/music_facts" }
library-search = { path = "../../components/library_search" }
chrono = "0.4"
nng = "1.0"
serde_json = "1.0"
library-service = { path = "../../components/library_service_stub", package = "library-service-stub" }
bdd-runner = { path = "../../bases/bdd-runner" }
