[package]
name = "fact-store"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata.polylith]
interface = "fact-store"

[dependencies]
acid-protocol = { path = "../acid_protocol" }
stainless-facts = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
