[package]
name = "gateway-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata]

[package.metadata.polylith]
interface = "gateway-client"

[dependencies]
acid-protocol = { workspace = true }
gateway-protocol = { workspace = true }
source-protocol = { workspace = true }
library-ipc-protocol = { workspace = true }
media-protocol = { workspace = true }
nng-transport = { workspace = true }
nng = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
