[package]
name = "media-protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata]

[package.metadata.polylith]
interface = "media-protocol"

[dependencies]
playback-primitives = { path = "../playback_primitives" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
pretty_assertions = { workspace = true }
