[package]
name = "inbox-utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata]

[package.metadata.polylith]
interface = "inbox-utils"

[dependencies]
tracing = { workspace = true }
zip = "2"

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest = { workspace = true }
tempfile = "3"
