[package]
name = "mdma-client"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata]

[package.metadata.polylith]
interface = "mdma-client"

[dependencies]
# IPC clients
library-ipc-client = { workspace = true }
library-ipc-protocol = { workspace = true }
library-search = { workspace = true }
media-client = { workspace = true }
media-protocol = { workspace = true }
gateway-client = { workspace = true }
source-protocol = { workspace = true }
nng-transport = { workspace = true }

# NNG + serialization
nng = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
