[package]
name = "mdma-playback"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "mdma-playback"
path = "src/main.rs"

[dependencies]
playback-engine = { path = "../../components/playback_engine" }
media-protocol = { path = "../../components/media_protocol" }
event-protocol = { path = "../../components/event_protocol" }
music-facts = { path = "../../components/music_facts" }
stainless-facts = { git = "https://github.com/johlrogge/stainless_facts" }
tokio = { workspace = true, features = ["full"] }
color-eyre = { workspace = true }
clap = { workspace = true, features = ["derive", "env"] }
parking_lot = { workspace = true }
nng = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = "0.3"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
