[package]
name = "audio-decoder"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
audio-types = { path = "../audio_types" }
thiserror = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }

symphonia = { version = "0.5", features = ["default", "flac", "mp3"] }

[build-dependencies]
hound = "3.5"
anyhow = "1.0"
symphonia = { version = "0.5", features = ["flac", "mp3"] }

[[bench]]
name = "track_loading"
harness = false

[dev-dependencies]
pretty_assertions = { workspace = true }
criterion = "0.5"
