[package]
name = "playback-primitives"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata]

[package.metadata.polylith]
interface = "playback-primitives"

[dependencies]
thiserror.workspace = true
serde = { workspace = true }
chrono = { workspace = true }
music-primitives = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
assert_matches.workspace = true
serde_json = { workspace = true }
rstest = { workspace = true }
