[package]
name = "mdma-beacon"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "beacon"
path = "src/main.rs"

[dependencies]
http-server = { path = "../../bases/http_server" }
storage_primitives = { path = "../../components/storage_primitives" }
tokio = { workspace = true }
color-eyre = { workspace = true }
axum = { workspace = true }
askama = { workspace = true }
tower-http = { workspace = true }
thiserror = { workspace = true }
clap = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-stream = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest = { workspace = true }
