[package]
name = "nng-transport"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata]

[package.metadata.polylith]
interface = "nng-transport"

[dependencies]
nng = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
dirs = "6"

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = "3"
