[package]
name = "track-formatter"
version = "0.1.0"
edition = "2021"
authors = ["MDMA Development Team"]
repository = "https://github.com/johlrogge/modular-digital-music-array"
license = "MIT"

[package.metadata]

[package.metadata.polylith]
interface = "track-formatter"

[dependencies]
library-ipc-protocol = { workspace = true }
colored = "2.0"
corsett = { git = "https://github.com/johlrogge/corsett.git", rev = "bf16c1aa2e8d6ba1f833e33009f2deecadc3ee26" }
