#!/bin/sh
exec 2>&1
sv check pipewire || exit 1
sleep 1
mkdir -p /run/mdma
chown mdma:mdma /run/mdma
rm -f /run/mdma/playback.sock
export PIPEWIRE_RUNTIME_DIR=/run/pipewire
cd /music
exec chpst -u mdma:mdma:audio:video:_pipewire /usr/bin/mdma-playback \
    --socket ipc:///run/mdma/playback.sock
