#!/bin/sh
exec 2>&1
sv check mdma-acid || exit 1
sv check mdma-audio || exit 1
sleep 1
mkdir -p /run/mdma
chown mdma:mdma /run/mdma
rm -f /run/mdma/playback.sock
export RUST_LOG=info
exec chpst -u mdma:mdma /usr/bin/mdma-playback \
	--socket ipc:///run/mdma/playback.sock \
	--acid-socket ipc:///run/mdma/acid.sock \
	--audio-socket ipc:///run/mdma/streams/audio.sock
