[package]
name = "acid-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
acid-protocol = { path = "../acid_protocol" }
nng = { workspace = true }
nng-transport = { path = "../nng_transport" }
serde_json = { workspace = true }

[features]
music = ["music-facts", "playback-primitives"]

[dependencies.music-facts]
package = "music-facts"
path = "../music_facts"
optional = true

[dev-dependencies]
pretty_assertions = { workspace = true }

[dependencies.playback-primitives]
package = "playback-primitives"
path = "../playback_primitives"
optional = true
