[package]
name = "acid-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
acid_protocol = { path = "../acid_protocol" }
nng = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[features]
music = ["music-facts", "playback-primitives"]

[dependencies.music-facts]
package = "music-facts"
path = "../music_facts"
optional = true

[dependencies.playback-primitives]
package = "playback-primitives"
path = "../playback_primitives"
optional = true
