[package]
name = "mdma-library"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "mdma-library"
path = "src/main.rs"

[dependencies]
service = { workspace = true }
library-service = { path = "../../components/library_service" }
clap = { workspace = true }
tokio = { workspace = true }
color-eyre = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
