[package]
name = "mdma-gateway"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "mdma-gateway"
path = "src/main.rs"

[dependencies]
event-protocol = { path = "../../components/event_protocol" }
gateway-protocol = { path = "../../components/gateway_protocol" }
source-protocol = { path = "../../components/source_protocol" }
library-ipc-protocol = { path = "../../components/library_ipc_protocol" }
media-protocol = { path = "../../components/media_protocol" }
nng = { workspace = true }
serde_json = { workspace = true }
clap = { workspace = true }
color-eyre = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
