[package]
name = "date-expression"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata]

[package.metadata.polylith]
interface = "date-expression"

[dependencies]
chrono = { workspace = true }
thiserror = { workspace = true }

