[package]
name = "stream-source-protocol"
version = "0.1.0"
edition = "2021"

[package.metadata]

[package.metadata.polylith]
interface = "stream-source-protocol"

[dependencies]
serde = { version = "1", features = ["derive"] }
music-primitives = { workspace = true }
playback-primitives = { workspace = true }

[dev-dependencies]
serde_json = "1.0"
pretty_assertions = "1"
