[package]
name = "gateway-protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata]

[package.metadata.polylith]
interface = "gateway-protocol"

[dependencies]
acid-protocol = { workspace = true }
source-protocol = { workspace = true }
library-ipc-protocol = { workspace = true }
media-protocol = { workspace = true }
playback-primitives = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
