[package]
name = "library-ipc-client"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata]

[package.metadata.polylith]
interface = "library-ipc-client"

[dependencies]
library-ipc-protocol = { workspace = true }
nng-transport = { workspace = true }
nng = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
