[package]
name = "library-ipc-protocol"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[package.metadata]

[package.metadata.polylith]
interface = "library-ipc-protocol"

[dependencies]
library-search = { path = "../library_search" }
music-facts = { path = "../music_facts" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest = { workspace = true }
