[package]
name = "mdma-console"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "mdma-console"
path = "src/main.rs"

[dependencies]
http-server = { path = "../../bases/http_server" }
audio-transcoder = { path = "../../components/audio_transcoder" }
inbox-utils = { path = "../../components/inbox_utils" }
library-ipc-client = { path = "../../components/library_ipc_client" }
gateway-client = { path = "../../components/gateway_client" }
source-protocol = { path = "../../components/source_protocol" }
event-protocol = { path = "../../components/event_protocol" }
nng-transport = { path = "../../components/nng_transport" }
media-protocol = { path = "../../components/media_protocol" }
library-search = { path = "../../components/library_search" }
bandcamp-api = { path = "../../components/bandcamp_api" }
tokio = { workspace = true }
color-eyre = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
nng = { workspace = true }
async-stream = { workspace = true }
axum = { workspace = true, features = ["multipart"] }
askama = { workspace = true }
tower-http = { workspace = true }
clap = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
rstest = { workspace = true }
